version: "3"
services:
  mongodb:
    container_name: gpt-db
    image: mongo:6.0.8-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - gpt-bot

volumes:
  mongo-data:
    name: gpt-db

networks:
  gpt-bot:
    name: gpt-bot